### ISSUE TITLE
Question about the training data

### ISSUE THREAD

**Issue by luofuli** [Helsinki-NLP/Tatoeba-Challenge#1]
Hi, this repo is excellent!!! I have a question about where the training data come from.

In `README.md`, you mentioned that `training data are taken from OPUS`.  When I search the English-Chinese parallel data on OPUS, there are only 31.2M parallel sentences. 

![image](https://user-images.githubusercontent.com/13479945/88461056-45a3b780-ced3-11ea-96fe-b39b12845e3e.png)

However, there are 41.6M parallel sentences in [https://github.com/Helsinki-NLP/Tatoeba-Challenge/blob/master/Data.md](https://github.com/Helsinki-NLP/Tatoeba-Challenge/blob/master/Data.md). So I wonder why the training parallel sentences of Tatoeba is bigger than opus website?

By the way, how can I download all the data more easily? (not one by one download from the link in `Data.md`)

**Comment by jorgtied** [comment]
The Tatoeba challenge data includes all Chinese language/spelling variants that are also sometimes inconsistently tagged in OPUS.

**Comment by luofuli** [comment]
Thanks.
