### ISSUE TITLE
question on reproduce model

### ISSUE THREAD

**Issue by jackie930** [Helsinki-NLP/Tatoeba-Challenge#23]
hi, awesome work! 
This is Jackie and i am trying to reproduce some model training work from scratch to better understand the machine translation domain. And I have two questions below:

> 
> 1) Is there any experiment details on how long it takes to train a model and what's the hyper-parameter setting?
> 2) regarding to model details & model comparison, like t5 vs general seq2seq, any files i can refer to?

thanks a lot!

**Comment by jorgtied** [comment]
I use the pipelines in `https://github.com/Helsinki-NLP/OPUS-MT-train`  and that includes all kinds of hyper-parameters and settings. However, it might not easy to dig the information out of the makefiles. As I use MarianNMT maybe examples in the mariannmt repository can help you? https://github.com/marian-nmt/marian-examples/tree/master/transformer

About t5: As far as I know this is also just a transformer seq2seq model. Just the idea is different that this is trained with various task to provide a flexible pre-trained model that can be fine-tuned for lots of different things. But there is plenty of information on various sources where you can get more details. Maybe check the documentation at huggingface and their course material can help?

**Comment by jackie930** [comment]
> I use the pipelines in `https://github.com/Helsinki-NLP/OPUS-MT-train` and that includes all kinds of hyper-parameters and settings. However, it might not easy to dig the information out of the makefiles. As I use MarianNMT maybe examples in the mariannmt repository can help you? https://github.com/marian-nmt/marian-examples/tree/master/transformer
> 
> About t5: As far as I know this is also just a transformer seq2seq model. Just the idea is different that this is trained with various task to provide a flexible pre-trained model that can be fine-tuned for lots of different things. But there is plenty of information on various sources where you can get more details. Maybe check the documentation at huggingface and their course material can help?

thanks!
