### ISSUE TITLE
How do i use these models?

### ISSUE THREAD

**Issue by Hammyhamm89** [Helsinki-NLP/Tatoeba-Challenge#24]

**Comment by Hammyhamm89** [comment]
hello?

**Comment by jorgtied** [comment]
You can use them with Marian-NMT. There is also the docker or the server setup provided from OPUS-MT if that helps you:
https://github.com/Helsinki-NLP/OPUS-MT

**Comment by Hammyhamm89** [comment]
> You can use them with Marian-NMT. There is also the docker or the server setup provided from OPUS-MT if that helps you: https://github.com/Helsinki-NLP/OPUS-MT

But i have no experience in programming

**Comment by jorgtied** [comment]
There is no programming involved but some installation and program setup is required. Otherwise, you could also try OPUS-CAT for running models on your local (windows) machine: https://helsinki-nlp.github.io/OPUS-CAT/

**Comment by Hammyhamm89** [comment]
yooo thanks so much

**Comment by Hammyhamm89** [comment]
> There is no programming involved but some installation and program setup is required. Otherwise, you could also try OPUS-CAT for running models on your local (windows) machine: https://helsinki-nlp.github.io/OPUS-CAT/

ah my cpu doesn't support AVX.... :(

**Comment by jorgtied** [comment]
Some models you can test with
* https://github.com/Helsinki-NLP/OPUS-MT-app/
* https://github.com/XapaJIaMnu/translateLocally
* https://huggingface.co/Helsinki-NLP
* https://live.european-language-grid.eu/
However, not all models are available there.

**Comment by Hammyhamm89** [comment]
> 

i discovered a solution, but i sometimes get translation service error, is this normal?

**Comment by jorgtied** [comment]
You need to be a bit more specific in order to get any help. What kind of solution? What are you testing and how?

**Comment by Hammyhamm89** [comment]
> You need to be a bit more specific in order to get any help. What kind of solution? What are you testing and how?

solution: virtual machine
Testing: caucasian language models
How: what do you mean?

**Comment by jorgtied** [comment]
Did you start a virtual machine running Ubuntu with OPUS-MT installed according to the websocket solution? Or did you use the dockerized version of OPUS-MT to run on a virtual machine? Or is it some other kind of solution?

By the way, I believe that the Caucasian model might not be very good. Be aware of limitations!
