### ISSUE TITLE
Issue with the download of the latest French-English (Fr-En) model

### ISSUE THREAD

**Issue by maxiek0071** [Helsinki-NLP/Tatoeba-Challenge#25]
Hello,

I would like to download the [Transformer Big Fr-En](https://github.com/Helsinki-NLP/Tatoeba-Challenge/tree/master/models/fra-eng#opustcv20210807bt_transformer-big_2022-03-09zip) model. In order to do this, I execute the following command:

`wget https://object.pouta.csc.fi/Tatoeba-MT-models/fra-eng/opusTCv20210807+bt_transformer-big_2022-03-09.zip`

![image](https://user-images.githubusercontent.com/45405419/169795412-887f5449-94bd-4c1c-90ec-78df671c4e09.png)

The download stalls always at 688MB, and it doesn't continue. Otherwise, I don't have any network issues on my virtual machine.

Could someone look into this?

Thanks.

**Comment by maxiek0071** [comment]
When trying to download a different Fr-En model, a 503 error code is displayed:

![image](https://user-images.githubusercontent.com/45405419/169796017-98f739ef-ef28-46b9-93c0-8e73f5b095cd.png)

**Comment by jorgtied** [comment]
It should be up and running again.

**Comment by maxiek0071** [comment]
Yes, it works, thanks.
