### ISSUE TITLE
Where is the testset data?

### ISSUE THREAD

**Issue by David-hg** [Helsinki-NLP/Tatoeba-Challenge#26]
Hi, I am training an eng-spa model and I would like to compare it to the ones already available. The problem is that the only testset file I can find is [this one](https://github.com/Helsinki-NLP/Tatoeba-Challenge/tree/master/data/test/eng-spa), which is not divided like the results obtained in [this model](https://github.com/Helsinki-NLP/Tatoeba-Challenge/tree/master/models/eng-spa). Where can I find the testset divided like this?

**Comment by David-hg** [comment]
Thanks for the quick reply. I now have all the tatoeba test sets but in most models there are more testsets used like newstest or tico19. is there any common version that can be used? I have found the tico19 test set in OPUS but it contains 3.1k sentences instead of the 2.1k it indicates in the benchmark from the model I mentioned in the first post.

**Comment by jorgtied** [comment]
Ah - I see - you mean the other test sets. Look here: https://github.com/Helsinki-NLP/OPUS-MT-testsets/

**Comment by David-hg** [comment]
Thank you very much, this was exactly what I was looking for!
