### ISSUE TITLE
uzb-eng - Invalid download link

### ISSUE THREAD

**Issue by ples** [Helsinki-NLP/Tatoeba-Challenge#27]
Hi. I am trying to download the model from here: https://github.com/Helsinki-NLP/Tatoeba-Challenge/tree/master/models/uzb-eng, but the link seems to be invalid. I am getting such response:
`<?xml version="1.0" encoding="UTF-8"?><Error><Code>NoSuchKey</Code><BucketName>Tatoeba-MT-models</BucketName><RequestId>tx000000000000000b4bb00-0062a1d8d3-3169a29e-allas-prod-kaj</RequestId><HostId>3169a29e-allas-prod-kaj-cpouta-production</HostId></Error>`

**Comment by jorgtied** [comment]
Ah sorry, I removed models that have very low scores. Basically, the quality is just too low to be useful for anything. Apologies for the broken link.

**Comment by ples** [comment]
@jorgtied Is there a way of how I can have these missing models? Alternative models repos? Or better try to train the model bymyself?
