### ISSUE TITLE
License clarification

### ISSUE THREAD

**Issue by Godnoken** [Helsinki-NLP/Tatoeba-Challenge#29]
Hi there,

I have noticed some contradictions in the licensing of these models.
On this repo, the license attached is CC BY-NC-SA 4.0, however, the [Opus-MT](https://github.com/Helsinki-NLP/Opus-MT) and [Opus-MT-train](https://github.com/Helsinki-NLP/OPUS-MT-train) READMEs tell me that the models are available under CC BY 4.0 license.

Which stated license is the correct one?

*Edit*

I found this response from almost three years ago: https://github.com/Helsinki-NLP/OPUS-MT-train/issues/12#issuecomment-629377495

But it would still be great with a final, updated clarification on this.

Thank you.

**Comment by jorgtied** [comment]
The data sets linked from the repository are distributed with a CC BY-NC-SA 4.0 license but the released models are with CC BY 4.0.

**Comment by Godnoken** [comment]
That's excellent Jörg, thank you.

I hope to be able to contribute to the collection of models towards the end of the year if things go as planned for me.

**Comment by haooxia** [comment]
> The data sets linked from the repository are distributed with a CC BY-NC-SA 4.0 license but the released models are with CC BY 4.0.

Hi @jorgtied,

I noticed that the released model is licensed under **CC-BY-4.0**, while its training data is labeled as **CC BY-NC-SA**.

After further investigation, I found that the training data is sourced from the **OPUS collection**. Most of the OPUS sub-corpora appear to have either unknown licenses or licenses that allow commercial use, with only a small subset explicitly marked as **Non-Commercial (NC)**.

I would like to clarify the following points:

Is the NC designation of the Tatoeba training dataset due to the inclusion of a small portion of NC-licensed OPUS sub-corpora, or due to the additional filtering, cleaning, or reorganization steps performed by Tatoeba on top of the OPUS data?

Given that the training data is labeled as NC, is the released model itself—licensed under CC-BY—still intended to be usable for commercial inference or deployment?

Thank you very much for your time and clarification.

**Comment by jorgtied** [comment]
Yes, exactly. It's because of the data from all kinds of sources. But the models are available for commercial use.

**Comment by haooxia** [comment]
> Yes, exactly. It's because of the data from all kinds of sources. But the models are available for commercial use.

Thank you for your explanation and your excellent work!

**Comment by haooxia** [comment]
> Yes, exactly. It's because of the data from all kinds of sources. But the models are available for commercial use.

Hi @jorgtied,

Thank you again to you and your team at Helsinki-NLP for your long-standing efforts and valuable contributions to the OPUS-MT and Tatoeba Challenge projects.

While organizing and using the models released by your team, I noticed that Helsinki-NLP has published multiple model repositories and model versions over the years. I therefore wanted to ask for your help in clarifying and confirming a few details, to ensure that my understanding is correct.

Specifically, I understand that you have released two repositories containing the original trained models:

1. The earlier OPUS-MT training models repository: https://github.com/Helsinki-NLP/OPUS-MT-train/tree/master/models
2. The more recent Tatoeba Challenge models repository: https://github.com/Helsinki-NLP/Tatoeba-Challenge/tree/master/models

Both repositories contain original Marian/NMT trained model weights for various language pairs.

In addition, I noticed that the Helsinki-NLP models published on Hugging Face (https://huggingface.co/Helsinki-NLP/models) are converted from these original models (for example, using the model [conversion scripts](https://github.com/huggingface/transformers/blob/main/src/transformers/models/marian/convert_marian_to_pytorch.py) provided in the Transformers library). Among the models released on Hugging Face, different language pairs are associated with different license declarations, for example:

1. Apache-2.0:
https://huggingface.co/Helsinki-NLP/opus-mt-en-es
https://huggingface.co/Helsinki-NLP/opus-mt-en-it

2. CC-BY-4.0:
https://huggingface.co/Helsinki-NLP/opus-mt-zh-en
https://huggingface.co/Helsinki-NLP/opus-mt-en-de

Therefore, can you please kindly confirm the following understanding is correct:

The models and corresponding weights trained on OPUS / Tatoeba Challenge datasets, including both the original weights released in the two repositories and the weights that were converted and released on Hugging Face and are already labeled as Apache-2.0 or CC-BY-4.0, can be used for commercial purposes.

Thank you very much for your time and consideration.

Best regards

**Comment by Mingle29** [comment]
also have the same confusion
