### ISSUE TITLE
encdoing issue 

### ISSUE THREAD

**Issue by 106AbdulBasit** [Helsinki-NLP/Tatoeba-Challenge#31]
I have downloaded the test .text file from the below link, which is basically the test set of eng- urdu,

[link](https://object.pouta.csc.fi/Tatoeba-MT-models/eng-urd/opus+bt-2021-03-12.test.txt)

The file has the following  like pairs 

Franco has blue jeans.
ÙØ±Ø§Ù†Ú©Ùˆ Ú©Û’ Ù¾Ø§Ø³ Ù†ÛŒÙ„ÛŒ Ø¬ÛŒÙ†Ø² ÛÛ’Û”
Ù„ÛŒÙˆÙ† Ú©Û’ Ù¾Ø§Ø³ Ù†ÛŒÙ„Ø§ Ø¬ÛŒÙ†Ø² ÛÛ’.

which encoding will be used, I have used "utf-8", "cp1256", "iso-8859-6" and many more, not able to process these lines,

**Comment by jorgtied** [comment]
It should be in UTF-8.

**Comment by 106AbdulBasit** [comment]
Surprisingly when the file was opened in the  Mac it was doing well .
