### ISSUE TITLE
some module have missed

### ISSUE THREAD

**Issue by 7zhanghao** [Helsinki-NLP/Tatoeba-Challenge#4]
In the npz file of the model you saved, it seems that the w in the Logitout layer is not given. Is this an oversight?
![image](https://user-images.githubusercontent.com/46468492/93840507-38ccf580-fcc3-11ea-8a77-2325507a7fa1.png)

**Comment by 7zhanghao** [comment]
Another question is that the order of  modules you save is different from that saved by torch.load.  l1 is the first layer, context stands for mask multihead attention, and ln stands for layer norm. Do you mean this?

**Comment by jorgtied** [comment]
Those models are created by MarianNMT and maybe you need to ask for support from there support channels or maybe I misunderstand something in your question. This is not a native torch package if that is causing some problem for you.

**Comment by 7zhanghao** [comment]
> Those models are created by MarianNMT and maybe you need to ask for support from there support channels or maybe I misunderstand something in your question. This is not a native torch package if that is causing some problem for you.

Thanks a lot.
