### ISSUE TITLE
Indonesian missing?

### ISSUE THREAD

**Issue by jvamvas** [Helsinki-NLP/Tatoeba-Challenge#5]
Thank you for providing this great resource!

It seems that Indonesian is not part of the Challenge right now. On Opus, there are 11.8M sentence pairs for Indonesian–English alone. Was Indonesian left out on purpose?

**Comment by jorgtied** [comment]
Indonesian is part of the 'msa' models as we use Macro-languages as specified in ISO639 standards.

**Comment by jvamvas** [comment]
Thanks!
