### ISSUE TITLE
Dataset server down?

### ISSUE THREAD

**Issue by dannigt** [Helsinki-NLP/Tatoeba-Challenge#6]
Hi there,

First thanks a lot for releasing the dataset!

The download links in https://github.com/Helsinki-NLP/Tatoeba-Challenge/blob/master/Data.md gave me the following error:
```
503 Service Unavailable
No server is available to handle this request. 
```
It seems the server is down? Thanks in advance for looking into it.

Best
Danni

**Comment by jorgtied** [comment]
Yes, unfortunately, the server is down. Hopefully it will come back online today. Apologies for the inconvenience ....

**Comment by dannigt** [comment]
Hi, I can reach the server now. Thanks a lot!

Best,
Danni
