### ISSUE TITLE
Missing particular language pair: eng-deu

### ISSUE THREAD

**Issue by bricksdont** [Helsinki-NLP/Tatoeba-Challenge#7]
Dear Jörg

I was looking for the specific language pair English-German, but it seems there is no data zip folder for this, i.e.

https://object.pouta.csc.fi/Tatoeba-Challenge/eng-deu.tar

does not exist.

Is there are reason why this does not exist?

Thanks and best
Mathias

**Comment by jorgtied** [comment]
Look for deu-eng instead. I only keep data sets in alphabetical order of their language IDs and consider them to symmetrical. Does that help?

**Comment by bricksdont** [comment]
thanks! that certainly helps and I have to admit the question is a bit silly in retrospect :)
