### ISSUE TITLE
Abk-Eng

### ISSUE THREAD

**Issue by QazQazaq** [Helsinki-NLP/Tatoeba-Challenge#9]
The data has many lines which are not parallel and has many blank lines.
https://object.pouta.csc.fi/Tatoeba-Challenge/abk-eng.tar

**Comment by jorgtied** [comment]
OK - good to know. Do you know where those lines come from? There is the *.id file that tells you about the source. It would be good to know more about the origin to find ways of cleaning the data or avoiding such case. Blank lines should, of course, be excluded in any case. I typically run additional pre-processing that filters out certain noise. I would recommend the same for anyone who wants to use the data.

**Comment by QazQazaq** [comment]
JW300

**Comment by jorgtied** [comment]
Hm - looks like they are still there even in the new release. I guess you need to filter them out. Sorry for that ...
